#import <Streams/GenericTransformStream.idl>
#import <Streams/CompressionFormat.idl>
[Exposed=*]
interface CompressionStream {
	constructor(CompressionFormat format);
};
CompressionStream includes GenericTransformStream;
